# Generated by Django 5.2.14 on 2026-05-20 07:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0003_customer_products'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_date', models.DateField(verbose_name='Satış Tarihi')),
                ('sale_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Satış Tutarı (₺)')),
                ('status', models.CharField(choices=[('completed', 'Tamamlandı'), ('pending', 'Beklemede'), ('cancelled', 'İptal')], default='completed', max_length=20, verbose_name='Durum')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notlar')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_leads', to=settings.AUTH_USER_MODEL, verbose_name='Satış Temsilcisi')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_leads', to='customers.customer', verbose_name='Müşteri')),
            ],
            options={
                'verbose_name': 'Satış Kaydı',
                'verbose_name_plural': 'Satış Kayıtları',
                'ordering': ['-sale_date', '-created_at'],
            },
        ),
    ]
