# Generated by Django 5.2.14 on 2026-05-20 12:38

import django.db.models.deletion
from django.db import migrations, models


def migrate_legacy_payments_and_products(apps, schema_editor):
    SalesLead = apps.get_model('sales_leads', 'SalesLead')
    SalesLeadInterimPayment = apps.get_model('sales_leads', 'SalesLeadInterimPayment')
    SalesLeadProductLine = apps.get_model('sales_leads', 'SalesLeadProductLine')

    for lead in SalesLead.objects.all():
        order = 0
        for field in ('interim_payment_1', 'interim_payment_2'):
            amount = getattr(lead, field, None)
            if amount is not None:
                SalesLeadInterimPayment.objects.create(
                    sales_lead_id=lead.pk,
                    amount=amount,
                    sort_order=order,
                )
                order += 1

        for idx, product in enumerate(lead.products.all()):
            SalesLeadProductLine.objects.create(
                sales_lead_id=lead.pk,
                product_id=product.pk,
                quantity=1,
                sort_order=idx,
            )


class Migration(migrations.Migration):

    dependencies = [
        ('core_settings', '0021_dynamic_payments_product_lines'),
        ('sales_leads', '0003_project_products_required'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesLeadInterimPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Tutar (₺)')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Sıra')),
                ('sales_lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interim_payments', to='sales_leads.saleslead', verbose_name='Satış kaydı')),
            ],
            options={
                'verbose_name': 'Ara ödeme',
                'verbose_name_plural': 'Ara ödemeler',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SalesLeadProductLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Adet')),
                ('note', models.CharField(blank=True, max_length=500, null=True, verbose_name='Ürün notu')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Sıra')),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_product_lines', to='core_settings.productcoloroption', verbose_name='Renk')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_product_lines', to='core_settings.productoption', verbose_name='Ürün')),
                ('sales_lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_lines', to='sales_leads.saleslead', verbose_name='Satış kaydı')),
            ],
            options={
                'verbose_name': 'Proje ürünü',
                'verbose_name_plural': 'Proje ürünleri',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.RunPython(migrate_legacy_payments_and_products, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='saleslead',
            name='interim_payment_1',
        ),
        migrations.RemoveField(
            model_name='saleslead',
            name='interim_payment_2',
        ),
    ]
