# Generated by Django 5.2.14 on 2026-05-20 11:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='profiles/', verbose_name='Profil fotoğrafı')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Telefon')),
                ('job_title', models.CharField(blank=True, max_length=120, verbose_name='Ünvan')),
                ('bio', models.TextField(blank=True, verbose_name='Hakkında')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kullanıcı profili',
                'verbose_name_plural': 'Kullanıcı profilleri',
            },
        ),
    ]
