# Generated by Django 5.2.14 on 2026-06-05 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_user_notification'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='usernotification',
            new_name='users_usern_user_id_134cff_idx',
            old_name='users_usern_user_id_8f0b0d_idx',
        ),
    ]
