# Generated by Django 5.2.14 on 2026-06-07 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_settings', '0052_plan'),
        ('users', '0012_rename_users_usern_user_id_8f0b0d_idx_users_usern_user_id_134cff_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='core_settings.plan', verbose_name='Abonelik planı'),
        ),
    ]
