# Generated by Django 5.2.14 on 2026-06-07 15:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_role_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImpersonationAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('start', 'Başlangıç'), ('stop', 'Bitiş')], max_length=10)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='impersonation_audits_as_actor', to=settings.AUTH_USER_MODEL)),
                ('target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='impersonation_audits_as_target', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Impersonate kaydı',
                'verbose_name_plural': 'Impersonate kayıtları',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='users_imper_created_5f4f47_idx'), models.Index(fields=['actor', '-created_at'], name='users_imper_actor_i_37ca9e_idx')],
            },
        ),
    ]
