# Generated by Django 5.2.14 on 2026-06-07 23:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_settings', '0057_plan_modules_and_panel_limits'),
        ('users', '0017_user_enabled_modules_strip_superuser_brands'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='platformauditlog',
            new_name='users_platf_created_77a7d9_idx',
            old_name='users_platf_created_6a0f0d_idx',
        ),
        migrations.RenameIndex(
            model_name='platformauditlog',
            new_name='users_platf_action_ee2a43_idx',
            old_name='users_platf_action_8c1b2a_idx',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='restaurant_brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restaurant_staff_profiles', to='core_settings.businessbrand', verbose_name='Restoran markası'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='restaurant_role',
            field=models.CharField(blank=True, choices=[('', '—'), ('store_owner', 'Kurum Yöneticisi'), ('manager', 'Operasyon Müdürü'), ('waiter', 'Servis Sorumlusu'), ('cashier', 'Finans Sorumlusu'), ('kitchen', 'Üretim Sorumlusu')], default='', max_length=20, verbose_name='Restoran POS rolü'),
        ),
    ]
