# Generated by Django 5.2.14 on 2026-05-16 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriorityOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(default='gray', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='StatusOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(default='blue', max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='productoption',
            name='icon',
            field=models.CharField(default='box', max_length=50),
        ),
        migrations.AlterField(
            model_name='productoption',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
