# Generated by Django 5.2.14 on 2026-05-16 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_settings', '0002_priorityoption_statusoption_productoption_icon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priorityoption',
            name='color',
            field=models.CharField(blank=True, default='gray', max_length=20),
        ),
        migrations.AlterField(
            model_name='statusoption',
            name='color',
            field=models.CharField(blank=True, default='blue', max_length=20),
        ),
    ]
