# Generated by Django 5.2.14 on 2026-05-16 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_settings', '0003_alter_priorityoption_color_alter_statusoption_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='company_address',
            field=models.TextField(blank=True, null=True, verbose_name='Firma Adresi'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='company_phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Firma Telefonu'),
        ),
    ]
