# Generated by Django 5.2.14 on 2026-05-16 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_settings', '0004_sitesettings_company_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Şablon Başlığı')),
                ('message', models.TextField(verbose_name='Mesaj İçeriği')),
            ],
            options={
                'verbose_name': 'WhatsApp Şablonu',
                'verbose_name_plural': 'WhatsApp Şablonları',
            },
        ),
    ]
