# Generated by Django 5.2.14 on 2026-05-16 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_settings', '0005_whatsapptemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='ai_chat_enabled',
            field=models.BooleanField(default=False, verbose_name='Yapay Zeka Sohbet Aktif'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='ai_system_prompt',
            field=models.TextField(blank=True, default='Sen bir asistanasın. Kullanıcının sorularını yanıtla ve ona yardımcı ol.', null=True, verbose_name='Yapay Zeka Sistem Talimatı'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='google_api_key',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Google AI (Gemini) API Key'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='openai_api_key',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='OpenAI API Key'),
        ),
    ]
