# Generated by Django 5.2.14 on 2026-05-18 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_settings', '0008_productoption_service_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolutionPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Ad')),
                ('partner_type', models.CharField(choices=[('subcontractor', 'Taşeron Firma'), ('logistics', 'Nakliye Aracı'), ('external_tech', 'Dış Servisçi'), ('other', 'Diğer')], default='subcontractor', max_length=20, verbose_name='Tür')),
                ('phone', models.CharField(blank=True, max_length=30, null=True, verbose_name='Telefon')),
                ('notes', models.CharField(blank=True, max_length=255, null=True, verbose_name='Not')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
            ],
            options={
                'verbose_name': 'Çözüm ortağı',
                'verbose_name_plural': 'Çözüm ortakları',
                'ordering': ['name'],
            },
        ),
    ]
