# Generated by Django 5.2.14 on 2026-05-18 22:58

import django.db.models.deletion
from django.db import migrations, models


def forwards_copy_partner_types(apps, schema_editor):
    SolutionPartner = apps.get_model('core_settings', 'SolutionPartner')
    SolutionPartnerType = apps.get_model('core_settings', 'SolutionPartnerType')

    mapping = {
        'subcontractor': 'Taşeron Firma',
        'logistics': 'Nakliye Aracı',
        'external_tech': 'Dış Servisçi',
        'other': 'Diğer',
    }
    created = {}
    for code, label in mapping.items():
        obj, _ = SolutionPartnerType.objects.get_or_create(name=label, defaults={'is_active': True})
        created[code] = obj

    for partner in SolutionPartner.objects.all():
        type_obj = created.get(partner.partner_type)
        if type_obj is None:
            fallback, _ = SolutionPartnerType.objects.get_or_create(name='Diğer', defaults={'is_active': True})
            type_obj = fallback
        partner.partner_type_ref_id = type_obj.id
        partner.save(update_fields=['partner_type_ref'])


class Migration(migrations.Migration):

    dependencies = [
        ('core_settings', '0009_solutionpartner_alter_priorityoption_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolutionPartnerType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='Tür adı')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
            ],
            options={
                'verbose_name': 'Çözüm ortağı türü',
                'verbose_name_plural': 'Çözüm ortağı türleri',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='solutionpartner',
            name='partner_type_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='partners_ref', to='core_settings.solutionpartnertype', verbose_name='Tür'),
        ),
        migrations.RunPython(forwards_copy_partner_types, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='solutionpartner',
            name='partner_type',
        ),
        migrations.RenameField(
            model_name='solutionpartner',
            old_name='partner_type_ref',
            new_name='partner_type',
        ),
        migrations.AlterField(
            model_name='solutionpartner',
            name='partner_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='partners', to='core_settings.solutionpartnertype', verbose_name='Tür'),
        ),
    ]
