# Generated by Django 5.2.14 on 2026-05-18 23:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_settings', '0010_solutionpartnertype_alter_priorityoption_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='Ekip adı')),
                ('company_phone', models.CharField(blank=True, max_length=30, null=True, verbose_name='Şirket hattı')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
            ],
            options={
                'verbose_name': 'Servis ekibi',
                'verbose_name_plural': 'Servis ekipleri',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='priorityoption',
            options={'verbose_name': 'Öncelik', 'verbose_name_plural': 'Öncelikler'},
        ),
        migrations.AlterModelOptions(
            name='productoption',
            options={'verbose_name': 'Ürün seçeneği', 'verbose_name_plural': 'Ürün seçenekleri'},
        ),
        migrations.AlterModelOptions(
            name='servicetypeoption',
            options={'verbose_name': 'Servis tipi', 'verbose_name_plural': 'Servis tipleri'},
        ),
        migrations.AlterModelOptions(
            name='statusoption',
            options={'verbose_name': 'Servis durumu', 'verbose_name_plural': 'Servis durumları'},
        ),
        migrations.AlterField(
            model_name='priorityoption',
            name='color',
            field=models.CharField(default='#3b82f6', max_length=7, verbose_name='Renk'),
        ),
        migrations.AlterField(
            model_name='productoption',
            name='color',
            field=models.CharField(default='#3b82f6', max_length=7, verbose_name='Renk'),
        ),
        migrations.AlterField(
            model_name='servicetypeoption',
            name='color',
            field=models.CharField(default='#3b82f6', max_length=7, verbose_name='Renk'),
        ),
        migrations.CreateModel(
            name='ServicePersonnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Ad Soyad')),
                ('company_phone', models.CharField(blank=True, max_length=30, null=True, verbose_name='Şirket numarası')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('notes', models.CharField(blank=True, max_length=255, null=True, verbose_name='Not')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personnel', to='core_settings.serviceteam', verbose_name='Ekip')),
            ],
            options={
                'verbose_name': 'Servis personeli',
                'verbose_name_plural': 'Servis personelleri',
                'ordering': ['name'],
            },
        ),
    ]
