# Generated by Django 5.2.14 on 2026-05-18 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_settings', '0011_serviceteam_alter_priorityoption_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicepersonnel',
            name='product_groups',
            field=models.ManyToManyField(blank=True, related_name='skilled_personnel', to='core_settings.productoption', verbose_name='Yetenekli ürün grupları'),
        ),
    ]
