# Generated by Django 5.2.14 on 2026-05-18 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_settings', '0012_servicepersonnel_product_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceteam',
            name='product_groups',
            field=models.ManyToManyField(blank=True, related_name='skilled_teams', to='core_settings.productoption', verbose_name='Yetenekli ürün grupları'),
        ),
    ]
