# Generated by Django 5.2.14 on 2026-05-19 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_settings', '0013_serviceteam_product_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='sidebar_profile_name',
            field=models.CharField(default='Yönetici', max_length=100, verbose_name='Sol Alt Profil Adı'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='sidebar_profile_role',
            field=models.CharField(default='Admin', max_length=100, verbose_name='Sol Alt Profil Ünvanı'),
        ),
    ]
