# Generated by Django 5.2.14 on 2026-05-19 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_settings', '0014_sitesettings_sidebar_profile_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='bulk_print_default_sort',
            field=models.CharField(choices=[('created_desc', 'Tarih (Yeni -> Eski)'), ('created_asc', 'Tarih (Eski -> Yeni)'), ('customer', 'Müşteri Adına Göre'), ('product', 'Ürüne Göre'), ('team', 'Ekibe Göre'), ('personnel', 'Personele Göre'), ('status', 'Duruma Göre'), ('priority', 'Önceliğe Göre')], default='created_desc', max_length=20, verbose_name='Toplu Yazdır Varsayılan Sıralama'),
        ),
    ]
