# Generated by Django 5.2.14 on 2026-05-20 08:39

from django.db import migrations, models


def seed_default_statuses(apps, schema_editor):
    from core_settings.status_defaults import ensure_default_statuses
    ensure_default_statuses()


class Migration(migrations.Migration):

    dependencies = [
        ('core_settings', '0016_personnelpayment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='statusoption',
            options={'ordering': ['sort_order', 'name'], 'verbose_name': 'Servis durumu', 'verbose_name_plural': 'Servis durumları'},
        ),
        migrations.AddField(
            model_name='statusoption',
            name='list_group',
            field=models.CharField(choices=[('active', 'Liste: varsayılan göster'), ('pending', 'Liste: isteğe bağlı (beklemede)'), ('hidden', 'Liste: varsayılan gizle')], default='active', max_length=20, verbose_name='Liste görünürlüğü'),
        ),
        migrations.AddField(
            model_name='statusoption',
            name='sort_order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Sıra'),
        ),
        migrations.RunPython(seed_default_statuses, migrations.RunPython.noop),
    ]
