# Generated by Django 5.2.14 on 2026-05-20 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_settings', '0017_statusoption_list_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='whatsapp_default_delay',
            field=models.PositiveSmallIntegerField(default=4, verbose_name='WhatsApp varsayılan bekleme (sn)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='whatsapp_skip_globally_default',
            field=models.BooleanField(default=False, verbose_name='WhatsApp: daha önce mesaj atılanları varsayılan atla'),
        ),
    ]
