# Generated by Django 5.2.14 on 2026-05-20 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_settings', '0020_whatsapptemplate_trigger_from_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsapptemplate',
            name='scenario',
            field=models.CharField(choices=[('service_created', 'Servis — ilk kayıt açılışı'), ('service_status', 'Servis — durum değişimi'), ('sales_lead_created', 'Satış — ilk kayıt'), ('sales_lead_status', 'Satış — durum değişimi'), ('customer_created', 'Müşteri — ilk kayıt')], default='service_status', max_length=40, verbose_name='Senaryo'),
        ),
        migrations.CreateModel(
            name='ProductColorOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(default='#3b82f6', max_length=7, verbose_name='Renk')),
                ('name', models.CharField(max_length=100, verbose_name='Renk adı')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='color_options', to='core_settings.productoption', verbose_name='Ürün')),
            ],
            options={
                'verbose_name': 'Ürün rengi',
                'verbose_name_plural': 'Ürün renkleri',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('product', 'name'), name='uniq_product_color_name')],
            },
        ),
    ]
