# Generated by Django 5.2.14 on 2026-05-31 12:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_settings', '0040_personnel_department'),
        ('customers', '0005_customermedia_compression'),
        ('sales_leads', '0006_sales_quote'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Hesap adı')),
                ('account_type', models.CharField(choices=[('cash', 'Nakit kasa'), ('bank', 'Banka'), ('pos', 'POS')], default='cash', max_length=10, verbose_name='Tür')),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Açılış bakiyesi (₺)')),
                ('is_default', models.BooleanField(default=False, verbose_name='Varsayılan')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Kasa / banka hesabı',
                'verbose_name_plural': 'Kasa / banka hesapları',
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.CreateModel(
            name='EExportSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advisor_note', models.TextField(blank=True, verbose_name='Mali müşavir notu')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Dış aktarım ayarları',
                'verbose_name_plural': 'Dış aktarım ayarları',
            },
        ),
        migrations.CreateModel(
            name='SupplierPayable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(max_length=120, verbose_name='Tedarikçi')),
                ('invoice_ref', models.CharField(blank=True, max_length=80, verbose_name='Fatura / referans')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Tutar (₺)')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Ödenen (₺)')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Vade')),
                ('notes', models.TextField(blank=True, verbose_name='Not')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tedarikçi borcu',
                'verbose_name_plural': 'Tedarikçi borçları',
                'ordering': ['due_date', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='financerecord',
            name='sales_lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_records', to='sales_leads.saleslead', verbose_name='Satış / proje'),
        ),
        migrations.AlterField(
            model_name='financerecord',
            name='category',
            field=models.CharField(blank=True, choices=[('', 'Genel'), ('rent', 'Kira'), ('fuel', 'Yakıt'), ('material', 'Malzeme'), ('office', 'Ofis'), ('marketing', 'Pazarlama'), ('payroll_other', 'Personel (diğer)'), ('supplier', 'Tedarikçi'), ('other', 'Diğer')], default='', help_text='Yalnızca gider kayıtlarında anlamlıdır.', max_length=20, verbose_name='Gider kategorisi'),
        ),
        migrations.AddField(
            model_name='financerecord',
            name='cash_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_records', to='core_settings.cashaccount', verbose_name='Hesap'),
        ),
        migrations.CreateModel(
            name='OperationalProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, verbose_name='Proje adı')),
                ('status', models.CharField(choices=[('planning', 'Planlama'), ('active', 'Aktif'), ('done', 'Tamamlandı'), ('cancelled', 'İptal')], default='active', max_length=20, verbose_name='Durum')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Başlangıç')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Bitiş')),
                ('notes', models.TextField(blank=True, verbose_name='Not')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operational_projects', to='customers.customer', verbose_name='Müşteri')),
                ('sales_lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operational_projects', to='sales_leads.saleslead', verbose_name='Satış kaydı')),
            ],
            options={
                'verbose_name': 'Operasyon projesi',
                'verbose_name_plural': 'Operasyon projeleri',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='financerecord',
            name='operational_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_records', to='core_settings.operationalproject', verbose_name='Operasyon projesi'),
        ),
        migrations.CreateModel(
            name='TimeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateField(verbose_name='Tarih')),
                ('hours', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Saat')),
                ('description', models.CharField(max_length=200, verbose_name='Açıklama')),
                ('billable', models.BooleanField(default=True, verbose_name='Faturalanabilir')),
                ('invoiced', models.BooleanField(default=False, verbose_name='Faturalandı')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='time_entries', to=settings.AUTH_USER_MODEL, verbose_name='Kaydeden')),
                ('operational_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='time_entries', to='core_settings.operationalproject', verbose_name='Proje')),
                ('personnel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='time_entries', to='core_settings.servicepersonnel', verbose_name='Personel')),
                ('sales_lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='time_entries', to='sales_leads.saleslead', verbose_name='Satış / proje')),
            ],
            options={
                'verbose_name': 'Zaman kaydı',
                'verbose_name_plural': 'Zaman kayıtları',
                'ordering': ['-entry_date', '-created_at'],
            },
        ),
    ]
