# Generated by Django 5.2.14 on 2026-06-03 11:08

import core_settings.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_settings', '0048_lean_kobi_defaults'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Marka / firma adı')),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('legal_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Ticari ünvan')),
                ('logo', models.ImageField(blank=True, null=True, upload_to=core_settings.models.business_brand_logo_upload_to, verbose_name='Logo')),
                ('phone', models.CharField(blank=True, default='', max_length=50, verbose_name='Telefon')),
                ('address', models.TextField(blank=True, default='', verbose_name='Adres')),
                ('currency_code', models.CharField(choices=[('TRY', 'Türk Lirası'), ('USD', 'ABD Doları'), ('EUR', 'Euro'), ('GBP', 'İngiliz Sterlini'), ('CHF', 'İsviçre Frangı'), ('AED', 'BAE Dirhemi'), ('SAR', 'Suudi Riyali')], default='TRY', max_length=3, verbose_name='Para birimi')),
                ('is_default', models.BooleanField(default=False, help_text='Eski kayıtlar ve üyeliksiz kullanıcılar için.', verbose_name='Sistem varsayılanı')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_brands', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
            ],
            options={
                'verbose_name': 'Marka / firma',
                'verbose_name_plural': 'Markalar / firmalar',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='financerecord',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finance_records', to='core_settings.businessbrand', verbose_name='Marka / firma'),
        ),
        migrations.AddField(
            model_name='servicepersonnel',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='personnel', to='core_settings.businessbrand', verbose_name='Marka / firma'),
        ),
        migrations.AddField(
            model_name='solutionpartner',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='solution_partners', to='core_settings.businessbrand', verbose_name='Marka / firma'),
        ),
        migrations.CreateModel(
            name='BrandMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Sahip'), ('member', 'Üye')], default='owner', max_length=20)),
                ('is_default', models.BooleanField(default=False, verbose_name='Varsayılan marka')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand_memberships', to=settings.AUTH_USER_MODEL)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='core_settings.businessbrand')),
            ],
            options={
                'verbose_name': 'Marka üyeliği',
                'verbose_name_plural': 'Marka üyelikleri',
                'constraints': [models.UniqueConstraint(fields=('user', 'brand'), name='uniq_brand_membership_user_brand')],
            },
        ),
    ]
