# Generated by Django 5.2.14 on 2026-06-05 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_settings', '0050_seed_default_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='warranty_days',
            field=models.PositiveIntegerField(default=0, verbose_name='Garanti Süresi (Gün)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='warranty_months',
            field=models.PositiveIntegerField(default=0, verbose_name='Garanti Süresi (Ay)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='warranty_years',
            field=models.PositiveIntegerField(default=1, verbose_name='Garanti Süresi (Yıl)'),
        ),
    ]
