# Generated by Django 5.2.14 on 2026-06-07 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_settings', '0051_sitesettings_warranty_days_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Plan adı')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Fiyat')),
                ('max_brands', models.PositiveIntegerField(default=1, verbose_name='Maksimum marka sayısı')),
                ('max_users_per_brand', models.PositiveIntegerField(default=3, verbose_name='Marka başına maksimum kullanıcı')),
                ('max_customers_per_brand', models.PositiveIntegerField(default=100, verbose_name='Marka başına maksimum müşteri')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
            ],
            options={
                'verbose_name': 'Plan',
                'verbose_name_plural': 'Planlar',
            },
        ),
    ]
