# Generated by Django 5.2.14 on 2026-06-07 14:16

from django.db import migrations


def seed_default_plans(apps, schema_editor):
    Plan = apps.get_model('core_settings', 'Plan')
    Plan.objects.get_or_create(
        name="Ücretsiz Plan",
        defaults={
            "price": 0.00,
            "max_brands": 1,
            "max_users_per_brand": 3,
            "max_customers_per_brand": 100,
            "is_active": True,
        }
    )
    Plan.objects.get_or_create(
        name="Pro Plan",
        defaults={
            "price": 199.00,
            "max_brands": 3,
            "max_users_per_brand": 10,
            "max_customers_per_brand": 1000,
            "is_active": True,
        }
    )
    Plan.objects.get_or_create(
        name="Kurumsal Plan",
        defaults={
            "price": 999.00,
            "max_brands": 10,
            "max_users_per_brand": 25,
            "max_customers_per_brand": 5000,
            "is_active": True,
        }
    )


class Migration(migrations.Migration):

    dependencies = [
        ('core_settings', '0052_plan'),
    ]

    operations = [
        migrations.RunPython(seed_default_plans),
    ]
