# Generated by Django 5.2.14 on 2026-06-08 00:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_first_owner(apps, schema_editor):
    BusinessBrand = apps.get_model('core_settings', 'BusinessBrand')
    BrandMembership = apps.get_model('core_settings', 'BrandMembership')
    for brand in BusinessBrand.objects.filter(first_owner__isnull=True):
        mem = (
            BrandMembership.objects.filter(
                brand=brand,
                role='owner',
            )
            .order_by('joined_at')
            .first()
        )
        if mem:
            brand.first_owner_id = mem.user_id
        elif brand.created_by_id:
            brand.first_owner_id = brand.created_by_id
        if brand.first_owner_id:
            brand.save(update_fields=['first_owner_id'])


class Migration(migrations.Migration):

    dependencies = [
        ('core_settings', '0057_plan_modules_and_panel_limits'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='businessbrand',
            name='first_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='founded_brands', to=settings.AUTH_USER_MODEL, verbose_name='İlk sahip'),
        ),
        migrations.AddField(
            model_name='plan',
            name='restaurant_plan_tier',
            field=models.CharField(blank=True, default='', help_text='starter, growth veya enterprise — boşsa plan adından türetilir.', max_length=20, verbose_name='KobiPOS plan kademesi'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_name',
            field=models.CharField(default='Kobi Hub', max_length=255),
        ),
        migrations.RunPython(backfill_first_owner, migrations.RunPython.noop),
    ]
