# Generated by Django 5.2.14 on 2026-06-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_settings', '0058_brand_first_owner_plan_tier'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='billing_days',
            field=models.PositiveIntegerField(
                default=30,
                help_text='Ödeme veya plan yükseltmede eklenen süre.',
                verbose_name='Abonelik dönemi (gün)',
            ),
        ),
        migrations.AddField(
            model_name='plan',
            name='trial_days',
            field=models.PositiveIntegerField(
                default=14,
                help_text='Yeni kayıt / ücretsiz planda marka aboneliğinin ilk süresi.',
                verbose_name='Deneme süresi (gün)',
            ),
        ),
    ]
