# Generated by Django 5.2.14 on 2026-05-16 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50, verbose_name='Durum')),
                ('priority', models.CharField(blank=True, max_length=50, null=True, verbose_name='Öncelik')),
                ('product_type', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ürün')),
                ('service_type', models.CharField(blank=True, max_length=255, null=True, verbose_name='Servis Tipi')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notlar')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
