# Generated by Django 5.2.14 on 2026-05-16 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerecord',
            name='status',
            field=models.CharField(choices=[('open', 'Açık'), ('ongoing', 'Devam Ediyor'), ('completed', 'Tamamlandı'), ('cancelled', 'İptal')], default='open', max_length=50, verbose_name='Durum'),
        ),
    ]
