# Generated by Django 5.2.14 on 2026-05-16 09:57

import django.db.models.deletion
import services.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_settings', '0001_initial'),
        ('services', '0003_alter_servicerecord_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicerecord',
            name='product_type',
        ),
        migrations.RemoveField(
            model_name='servicerecord',
            name='service_type',
        ),
        migrations.AddField(
            model_name='servicerecord',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core_settings.productoption', verbose_name='Ürün'),
        ),
        migrations.AddField(
            model_name='servicerecord',
            name='service_types',
            field=models.ManyToManyField(blank=True, to='core_settings.servicetypeoption', verbose_name='Servis Tipleri'),
        ),
        migrations.AddField(
            model_name='servicerecord',
            name='warranty_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Garanti Bitiş'),
        ),
        migrations.AddField(
            model_name='servicerecord',
            name='warranty_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Garanti Başlangıç'),
        ),
        migrations.AlterField(
            model_name='servicerecord',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_services', to=settings.AUTH_USER_MODEL, verbose_name='Atanan Kişi / Ekip'),
        ),
        migrations.AlterField(
            model_name='servicerecord',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Servis Notları'),
        ),
        migrations.AlterField(
            model_name='servicerecord',
            name='priority',
            field=models.CharField(choices=[('low', 'Düşük'), ('medium', 'Orta'), ('high', 'Acil')], default='medium', max_length=50, verbose_name='Öncelik'),
        ),
        migrations.AlterField(
            model_name='servicerecord',
            name='status',
            field=models.CharField(choices=[('open', 'Açık'), ('ongoing', 'Devam Ediyor'), ('completed', 'Tamamlandı'), ('cancelled', 'İptal'), ('paid_completed', 'Ücretli Tamamlandı'), ('paid_cancelled', 'İptal Ücretli')], default='open', max_length=50, verbose_name='Durum'),
        ),
        migrations.CreateModel(
            name='ServiceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='services.servicerecord')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=services.models.service_image_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='services.servicerecord')),
            ],
        ),
    ]
