# Generated by Django 5.2.14 on 2026-05-16 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_remove_servicerecord_product_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicerecord',
            name='warranty_end_date',
        ),
        migrations.AddField(
            model_name='servicerecord',
            name='warranty_years',
            field=models.PositiveIntegerField(default=2, verbose_name='Garanti Süresi (Yıl)'),
        ),
        migrations.AlterField(
            model_name='servicerecord',
            name='status',
            field=models.CharField(choices=[('open', 'Açık'), ('ongoing', 'Devam Ediyor'), ('completed', 'Tamamlandı'), ('cancelled', 'İptal'), ('paid_next', 'Sonrakine Ücretli Servis Yazılacak'), ('paid_service', 'Ücretli Servis'), ('paid_completed', 'Ücretli Tamamlandı'), ('paid_cancelled', 'İptal Ücretli')], default='open', max_length=50, verbose_name='Durum'),
        ),
    ]
