# Generated by Django 5.2.14 on 2026-05-16 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_remove_servicerecord_warranty_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicerecord',
            name='warranty_years',
        ),
        migrations.AddField(
            model_name='servicerecord',
            name='warranty_status',
            field=models.CharField(choices=[('active', 'Garanti Devam Ediyor'), ('expired', 'Garanti Bitti')], default='active', max_length=20, verbose_name='Garanti Durumu'),
        ),
    ]
