# Generated by Django 5.2.14 on 2026-05-16 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_settings', '0001_initial'),
        ('services', '0006_remove_servicerecord_warranty_years_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicerecord',
            name='product',
        ),
        migrations.RemoveField(
            model_name='servicerecord',
            name='warranty_start_date',
        ),
        migrations.AddField(
            model_name='servicerecord',
            name='contract_date',
            field=models.DateField(blank=True, null=True, verbose_name='Sözleşme Tarihi'),
        ),
        migrations.AddField(
            model_name='servicerecord',
            name='products',
            field=models.ManyToManyField(blank=True, to='core_settings.productoption', verbose_name='Ürünler'),
        ),
        migrations.AlterField(
            model_name='servicerecord',
            name='status',
            field=models.CharField(choices=[('service', 'Servis'), ('pending', 'Beklemede'), ('cancelled', 'İptal'), ('paid_next', 'Sonrakine Ücretli Servis Yazılacak'), ('paid_completed', 'Ücretli Tamamlandı'), ('paid_cancelled', 'İptal Ücretli')], default='service', max_length=50, verbose_name='Durum'),
        ),
    ]
