# Generated by Django 5.2.14 on 2026-05-16 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_settings', '0002_priorityoption_statusoption_productoption_icon_and_more'),
        ('services', '0007_remove_servicerecord_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerecord',
            name='priority',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core_settings.priorityoption', verbose_name='Öncelik'),
        ),
        migrations.AlterField(
            model_name='servicerecord',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core_settings.statusoption', verbose_name='Durum'),
        ),
    ]
