# Generated by Django 5.2.14 on 2026-05-16 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_alter_servicerecord_priority_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicerecord',
            name='contract_date',
        ),
    ]
