# Generated by Django 5.2.14 on 2026-05-18 22:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_settings', '0009_solutionpartner_alter_priorityoption_options_and_more'),
        ('services', '0009_remove_servicerecord_contract_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerecord',
            name='solution_partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_records', to='core_settings.solutionpartner', verbose_name='Çözüm ortağı'),
        ),
    ]
