# Generated by Django 5.2.14 on 2026-05-18 23:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_settings', '0011_serviceteam_alter_priorityoption_options_and_more'),
        ('services', '0010_servicerecord_solution_partner'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerecord',
            name='service_personnel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='core_settings.servicepersonnel', verbose_name='Servis personeli'),
        ),
    ]
