# Generated by Django 5.2.14 on 2026-05-19 00:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0011_servicerecord_service_personnel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_no', models.PositiveIntegerField(verbose_name='Versiyon No')),
                ('snapshot', models.JSONField(verbose_name='Servis Snapshot')),
                ('summary', models.CharField(blank=True, default='', max_length=255, verbose_name='Özet')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='services.servicerecord')),
            ],
            options={
                'ordering': ['-version_no'],
                'unique_together': {('service', 'version_no')},
            },
        ),
    ]
