# Generated by Django 5.2.14 on 2026-05-19 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0012_serviceversion'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicehistory',
            name='snapshot',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
