# Generated by Django 5.2.14 on 2026-06-03 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_settings', '0049_business_brands'),
        ('services', '0015_servicerecord_scheduled_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerecord',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='service_records', to='core_settings.businessbrand', verbose_name='Marka / firma'),
        ),
    ]
