# Generated by Django 5.2.14 on 2026-06-05 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0016_business_brands'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerecord',
            name='partner_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Ödenecek Ücret'),
        ),
    ]
