# Generated by Django 5.2.14 on 2026-06-05 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0017_servicerecord_partner_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerecord',
            name='warranty_note',
            field=models.TextField(blank=True, null=True, verbose_name='Garanti Açıklaması / Notu'),
        ),
    ]
