# Generated by Django 5.2.14 on 2026-05-16 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Müşteri Adı')),
                ('phone', models.CharField(blank=True, max_length=100, null=True, verbose_name='Telefon')),
                ('region', models.CharField(blank=True, max_length=255, null=True, verbose_name='Bölge')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Adres')),
                ('location_link', models.URLField(blank=True, max_length=500, null=True, verbose_name='Konum Linki')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
