# Generated by Django 5.2.14 on 2026-05-16 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='contract_date',
            field=models.DateField(blank=True, null=True, verbose_name='Sözleşme Tarihi'),
        ),
    ]
