# Generated by Django 5.2.14 on 2026-05-16 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_settings', '0005_whatsapptemplate'),
        ('customers', '0002_customer_contract_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='products',
            field=models.ManyToManyField(blank=True, to='core_settings.productoption', verbose_name='Satın Aldığı Ürünler'),
        ),
    ]
