# Generated by Django 5.2.14 on 2026-06-07 23:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_settings', '0057_plan_modules_and_panel_limits'),
        ('restaurant', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantcategory',
            name='icon',
            field=models.CharField(default='utensils', max_length=50),
        ),
        migrations.AddField(
            model_name='restaurantmenuitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='restaurant/menu/'),
        ),
        migrations.CreateModel(
            name='RestaurantAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('impersonate', 'Hesaba Gir'), ('brand_enter', 'Mağazaya Gir')], max_length=30)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restaurant_audit_actions', to=settings.AUTH_USER_MODEL)),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restaurant_audit_targets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RestaurantBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('panel_slug', models.SlugField(blank=True, max_length=80, null=True, unique=True)),
                ('panel_password', models.CharField(blank=True, max_length=128, null=True)),
                ('panel_enabled', models.BooleanField(default=False)),
                ('panel_password_updated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_branches', to='core_settings.businessbrand')),
            ],
            options={
                'verbose_name': 'Restoran şubesi',
                'verbose_name_plural': 'Restoran şubeleri',
                'unique_together': {('brand', 'name')},
            },
        ),
        migrations.AlterField(
            model_name='restauranttable',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='restaurant.restaurantbranch'),
        ),
        migrations.CreateModel(
            name='RestaurantCashRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cash_registers', to='restaurant.restaurantbranch')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_cash_registers', to='core_settings.businessbrand')),
            ],
            options={
                'unique_together': {('brand', 'name')},
            },
        ),
        migrations.CreateModel(
            name='RestaurantCashTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('in', 'Giriş'), ('out', 'Çıkış')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('register', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='restaurant.restaurantcashregister')),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantCourier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(default='available', max_length=50)),
                ('cash_advance_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_couriers', to='core_settings.businessbrand')),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantFranchisePanelToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=40, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='panel_tokens', to='restaurant.restaurantbranch')),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('stock_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('minimum_stock', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('unit', models.CharField(default='pcs', max_length=20)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_ingredients', to='core_settings.businessbrand')),
            ],
            options={
                'unique_together': {('brand', 'name')},
            },
        ),
        migrations.CreateModel(
            name='RestaurantMenuItemModifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price_extra', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('is_required', models.BooleanField(default=False)),
                ('is_available', models.BooleanField(default=True)),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modifiers', to='restaurant.restaurantmenuitem')),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('preparing', 'Hazırlanıyor'), ('ready', 'Hazır'), ('completed', 'Tamamlandı'), ('cancelled', 'İptal Edildi')], default='preparing', max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('discount_type', models.CharField(choices=[('none', 'İndirim Yok'), ('percent', 'Yüzde (%)'), ('fixed', 'Sabit (TL)')], default='none', max_length=10)),
                ('discount_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('discount_reason', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='restaurant.restaurantbranch')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_orders', to='core_settings.businessbrand')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='restaurant.restauranttable')),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantCourierLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='assigned', max_length=50)),
                ('courier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='restaurant.restaurantcourier')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courier_logs', to='restaurant.restaurantorder')),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('modifier_text', models.CharField(blank=True, max_length=500, null=True)),
                ('modifier_extra', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('status', models.CharField(choices=[('preparing', 'Hazırlanıyor'), ('ready', 'Hazır'), ('served', 'Servis Edildi'), ('cancelled', 'İptal Edildi')], default='preparing', max_length=20)),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.restaurantmenuitem')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='restaurant.restaurantorder')),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('cash', 'Nakit'), ('card', 'Kredi Kartı')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='restaurant.restaurantorder')),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Restoran', max_length=150)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('tax_office', models.CharField(blank=True, max_length=100, null=True)),
                ('tax_number', models.CharField(blank=True, max_length=50, null=True)),
                ('working_hours', models.CharField(default='09:00 - 23:00', max_length=100)),
                ('active_plan', models.CharField(default='Growth', max_length=50)),
                ('plan_expiry', models.DateField(blank=True, null=True)),
                ('website_slug', models.CharField(default='restoran', max_length=100)),
                ('website_theme_color', models.CharField(default='#6366f1', max_length=30)),
                ('website_banner_text', models.CharField(default='Hoş Geldiniz!', max_length=255)),
                ('website_enable_table_orders', models.BooleanField(default=True)),
                ('website_enable_delivery', models.BooleanField(default=True)),
                ('website_enable_takeaway', models.BooleanField(default=True)),
                ('website_custom_domain', models.CharField(blank=True, max_length=255, null=True)),
                ('website_about_text', models.TextField(blank=True, null=True)),
                ('website_instagram', models.CharField(blank=True, max_length=100, null=True)),
                ('website_facebook', models.CharField(blank=True, max_length=100, null=True)),
                ('website_template', models.CharField(default='Modern Dark', max_length=50)),
                ('website_enable_reservation', models.BooleanField(default=True)),
                ('ext_qr_menu_enabled', models.BooleanField(default=True)),
                ('ext_official_website_enabled', models.BooleanField(default=True)),
                ('ext_crm_enabled', models.BooleanField(default=True)),
                ('ext_whatsapp_enabled', models.BooleanField(default=False)),
                ('ext_live_courier_enabled', models.BooleanField(default=False)),
                ('brand', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_profile', to='core_settings.businessbrand')),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('instructions', models.TextField(blank=True, null=True)),
                ('menu_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recipe', to='restaurant.restaurantmenuitem')),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantRecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(default='pcs', max_length=20)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.restaurantingredient')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='restaurant.restaurantrecipe')),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantStaffMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(default='waiter', max_length=50)),
                ('hire_date', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('staff_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='restaurant.restaurantstaffmember')),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantStockAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
                ('total_variance_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_stock_audits', to='core_settings.businessbrand')),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantStockAuditItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_stock', models.DecimalField(decimal_places=2, max_digits=10)),
                ('actual_stock', models.DecimalField(decimal_places=2, max_digits=10)),
                ('variance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cost_difference', models.DecimalField(decimal_places=2, max_digits=12)),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='restaurant.restaurantstockaudit')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.restaurantingredient')),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantSubscriptionInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('plan', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid', models.BooleanField(default=False)),
                ('payment_provider', models.CharField(choices=[('mock', 'Mock'), ('stripe', 'Stripe'), ('iyzico', 'iyzico')], default='mock', max_length=20)),
                ('payment_status', models.CharField(choices=[('pending', 'Bekliyor'), ('paid', 'Ödendi'), ('failed', 'Başarısız'), ('cancelled', 'İptal')], default='pending', max_length=20)),
                ('external_id', models.CharField(blank=True, max_length=255, null=True)),
                ('checkout_url', models.URLField(blank=True, max_length=500, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_invoices', to='core_settings.businessbrand')),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantTenantProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('plan_tier', models.CharField(choices=[('starter', 'Starter'), ('growth', 'Growth'), ('enterprise', 'Enterprise')], default='starter', max_length=20)),
                ('plan_expiry', models.DateField(blank=True, null=True)),
                ('trial_started_at', models.DateTimeField(blank=True, null=True)),
                ('brand', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_tenant', to='core_settings.businessbrand')),
            ],
            options={
                'verbose_name': 'Restoran kiracı profili',
                'verbose_name_plural': 'Restoran kiracı profilleri',
            },
        ),
        migrations.CreateModel(
            name='RestaurantWhatsAppConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_number_id', models.CharField(blank=True, max_length=100, null=True)),
                ('is_auto_message_enabled', models.BooleanField(default=True)),
                ('message_template', models.TextField(default='Merhaba {customer_name}, {order_id} nolu siparişiniz alınmıştır.')),
                ('is_live_chat_enabled', models.BooleanField(default=False)),
                ('ask_admin_before_sending', models.BooleanField(default=True)),
                ('brand', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_whatsapp', to='core_settings.businessbrand')),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('total_orders', models.IntegerField(default=0)),
                ('last_order_date', models.DateField(blank=True, null=True)),
                ('subscription_status', models.CharField(default='active', max_length=30)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_customers', to='core_settings.businessbrand')),
            ],
            options={
                'unique_together': {('brand', 'phone')},
            },
        ),
        migrations.CreateModel(
            name='RestaurantOrderChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('api_key', models.CharField(blank=True, max_length=255, null=True)),
                ('endpoint_url', models.URLField(blank=True, max_length=255, null=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_order_channels', to='core_settings.businessbrand')),
            ],
            options={
                'unique_together': {('brand', 'name')},
            },
        ),
    ]
