"""Sistem izin kataloğu — (codename, ad, modül, tür, sıra, açıklama)."""

PERMISSION_KIND_ACCESS = 'access'
PERMISSION_KIND_ACTION = 'action'

PERMISSIONS = [
    ('access.home', 'Ana sayfa', 'Genel', PERMISSION_KIND_ACCESS, 10,
     'Portal ana sayfasına giriş.'),
    ('access.accounting', 'Muhasebe modülü', 'Muhasebe', PERMISSION_KIND_ACCESS, 20,
     'Maaş, avans, gelir-gider ve satış kayıtları (/muhasebe/).'),
    ('access.services', 'Yardım Masası modülü', 'Yardım Masası', PERMISSION_KIND_ACCESS, 40,
     'Yardım Masası özet paneli ve kayıt listesine erişim.'),
    ('access.contact', 'Rehber modülü', 'Rehber', PERMISSION_KIND_ACCESS, 45,
     'Rehber özeti, müşteri, firma ve ilgili sayfalara erişim.'),
    ('access.restaurant', 'Restoran modülü', 'Restoran', PERMISSION_KIND_ACCESS, 46,
     'Menü, masa ve restoran POS (/restoran/).'),
    ('access.outreach', 'İletişim Merkezi modülü', 'İletişim', PERMISSION_KIND_ACCESS, 48,
     'Kampanya gönderimi ve mesaj kayıtları (/iletisim/).'),
    ('access.tools', 'Araçlar modülü', 'Araçlar', PERMISSION_KIND_ACCESS, 50,
     'Araçlar ana sayfasına erişim.'),
    ('access.settings', 'Site genel ayarları', 'Ayarlar', PERMISSION_KIND_ACCESS, 60,
     'Ürün, arıza tipi, durum, öncelik ve firma bilgileri (/ayarlar/).'),

    ('services.manage', 'Servis kaydı oluştur & düzenle', 'Yardım Masası', PERMISSION_KIND_ACTION, 110,
     'Yeni servis, düzenleme ve listede durum/öncelik hızlı güncelleme.'),
    ('services.delete', 'Servis kaydı sil', 'Yardım Masası', PERMISSION_KIND_ACTION, 120,
     'Tekil ve toplu servis silme.'),
    ('services.bulk', 'Toplu servis işlemleri', 'Yardım Masası', PERMISSION_KIND_ACTION, 130,
     'Toplu durum/öncelik değiştirme ve personel atama.'),
    ('services.print', 'Servis yazdırma', 'Yardım Masası', PERMISSION_KIND_ACTION, 140,
     'Tekil ve toplu yazdırma.'),
    ('services.whatsapp', 'Servis WhatsApp gönderimi', 'Yardım Masası', PERMISSION_KIND_ACTION, 150,
     'Durum değişiminde WhatsApp onayı ve otomatik dağıtım.'),

    ('contact.customers_view', 'Müşteri listesi görüntüle', 'Rehber', PERMISSION_KIND_ACTION, 205,
     'Müşteri listesi, detay ve seçim API\'lerini salt okunur görüntüleme.'),
    ('contact.customers', 'Müşteri oluştur & düzenle', 'Rehber', PERMISSION_KIND_ACTION, 210,
     'Yeni müşteri, güncelleme, hızlı düzenleme ve toplu güncelleme.'),
    ('contact.customers_delete', 'Müşteri sil', 'Rehber', PERMISSION_KIND_ACTION, 220,
     'Müşteri kaydı silme ve toplu silme.'),
    ('contact.firms', 'Firma rehberi yönetimi', 'Rehber', PERMISSION_KIND_ACTION, 230,
     'Firma kazı, firma listesi.'),
    ('contact.teams', 'Ekip yönetimi', 'Rehber', PERMISSION_KIND_ACTION, 240,
     'Servis ekiplerini tanımlama, düzenleme ve silme.'),
    ('contact.personnel', 'Personel kayıtları', 'Rehber', PERMISSION_KIND_ACTION, 245,
     'Personeller ve yönetimi — departman, ünvan, ekip (/contact/personel/).'),
    ('contact.payroll', 'Maaş & avans kayıtları', 'Muhasebe', PERMISSION_KIND_ACTION, 250,
     'Personel maaş ve avans ödemesi ekleme ve silme.'),
    ('accounting.finance', 'Gelir & gider kayıtları', 'Muhasebe', PERMISSION_KIND_ACTION, 255,
     'Genel gelir ve gider hareketlerini kaydetme ve silme.'),
    ('contact.solution', 'Çözüm ağı yönetimi', 'Rehber', PERMISSION_KIND_ACTION, 260,
     'Çözüm ortağı ekleme, düzenleme ve silme.'),

    ('sales.manage', 'Satış kaydı oluştur & düzenle', 'Muhasebe', PERMISSION_KIND_ACTION, 310,
     'Yeni satış, düzenleme ve kayıt güncelleme.'),
    ('sales.delete', 'Satış kaydı sil', 'Muhasebe', PERMISSION_KIND_ACTION, 320,
     'Satış kaydı silme.'),
    ('sales.reports', 'Satış raporları', 'Muhasebe', PERMISSION_KIND_ACTION, 330,
     'Rapor ekranını görüntüleme.'),
    ('sales.export', 'Satış CSV dışa aktarım', 'Muhasebe', PERMISSION_KIND_ACTION, 340,
     'Rapor verisini CSV olarak indirme.'),

    ('tools.whatsapp', 'WhatsApp bağlan & mesaj', 'Araçlar', PERMISSION_KIND_ACTION, 410,
     'WhatsApp köprüsü, bağlantılar ve mesaj gönderme.'),
    ('tools.whatsapp_scenarios', 'WhatsApp senaryo şablonları', 'Araçlar', PERMISSION_KIND_ACTION, 420,
     'Durum senaryoları ve otomatik mesaj kuralları.'),
    ('tools.ai', 'Yapay zeka ayarları', 'Ayarlar', PERMISSION_KIND_ACTION, 430,
     'Site ayarlarında AI API, raporlama ve sohbet.'),
    ('tools.backup', 'Yedekleme & geri yükleme', 'Süper Admin', PERMISSION_KIND_ACTION, 440,
     'Süper admin panelinde tam SQLite yedeği alma ve geri yükleme.'),
    ('tools.media', 'Medya kütüphanesi', 'Araçlar', PERMISSION_KIND_ACTION, 450,
     'Tüm yüklenen dosyaları görüntüleme ve önizleme.'),
    ('tools.media_delete', 'Medya silme', 'Araçlar', PERMISSION_KIND_ACTION, 455,
     'Medya kütüphanesinden dosya silme.'),
]

DEFAULT_ROLES = {
    'admin': {
        'name': 'Yönetici',
        'description': 'Tüm modül ve fonksiyon izinleri (süper admin paneli hariç).',
        'is_system': True,
        'permissions': [row[0] for row in PERMISSIONS if row[0] != 'tools.backup'],
    },
    'operation': {
        'name': 'Operasyon',
        'description': 'Servis, contact ve operasyon araçları.',
        'is_system': True,
        'permissions': [
            'access.home', 'access.services', 'access.contact', 'access.outreach', 'access.tools',
            'services.manage', 'services.bulk', 'services.print', 'services.whatsapp',
            'contact.customers_view', 'contact.customers', 'contact.firms', 'contact.teams', 'contact.personnel', 'contact.solution',
            'tools.whatsapp', 'tools.whatsapp_scenarios', 'tools.media', 'tools.media_delete',
        ],
    },
    'service': {
        'name': 'Servis Personeli',
        'description': 'Servis kayıtları ve müşteri görüntüleme.',
        'is_system': True,
        'permissions': [
            'access.home', 'access.services', 'access.contact',
            'services.manage', 'services.print', 'services.whatsapp',
            'contact.customers_view', 'contact.customers',
            'tools.media',
        ],
    },
    'sales': {
        'name': 'Satış Temsilcisi',
        'description': 'Muhasebe modülünde satış kayıtları ve müşteri erişimi.',
        'is_system': True,
        'permissions': [
            'access.home', 'access.accounting', 'access.contact',
            'sales.manage', 'sales.reports', 'sales.export',
            'contact.customers_view', 'contact.customers',
            'tools.media',
        ],
    },
    'accounting': {
        'name': 'Muhasebe',
        'description': 'Maaş, avans, gelir-gider, satış kayıtları ve müşteri görüntüleme.',
        'is_system': True,
        'permissions': [
            'access.home', 'access.accounting', 'access.contact',
            'contact.customers_view', 'contact.payroll', 'accounting.finance',
            'sales.manage', 'sales.reports', 'sales.export',
        ],
    },
}

ROUTE_PERMISSIONS = [
    ('/api/bildirimler/', None),
    ('/api/hizli-arama/', None),
    ('/restoran/', 'access.restaurant'),
    ('/panel/ekip/', 'access.home'),
    ('/yonetim/', None),
    ('/profil/', None),
    ('/chat/', None),
    ('/ayarlar/yedekler/', None),
    ('/yonetim/yedekler/', None),
    ('/iletisim/', 'access.outreach'),
    ('/contact/pazarlama/', 'access.outreach'),
    ('/ayarlar/ai/', 'tools.ai'),
    ('/ayarlar/etiketler/', 'access.settings'),
    ('/ayarlar/api/options/quick-update/', ('services.manage', 'access.settings')),
    ('/ayarlar/api/options/', ('access.services', 'access.settings')),
    ('/ayarlar/api/settings/', 'access.settings'),
    ('/ayarlar/', 'access.settings'),
    ('/services-dashboard/settings/', 'access.settings'),
    ('/services-dashboard/api/options/quick-create/', ('services.manage', 'access.settings')),
    ('/services-dashboard/api/options/quick-update/', ('services.manage', 'access.settings')),
    ('/services-dashboard/api/options/', ('access.services', 'access.settings')),
    ('/services-dashboard/api/settings/', 'access.settings'),
    ('/services-dashboard/services/takvim/', 'access.services'),
    ('/services-dashboard/services/bulk-delete/', 'services.delete'),
    ('/services-dashboard/services/bulk-manage/', 'services.bulk'),
    ('/services-dashboard/services/bulk-print/', 'services.print'),
    ('/services-dashboard/services/send-whatsapp/', 'services.whatsapp'),
    ('/services-dashboard/services/send-whatsapp-auto/', 'services.whatsapp'),
    ('/services-dashboard/services/new/', 'services.manage'),
    ('/services-dashboard/', 'access.services'),
    ('/muhasebe/satis/teklifler/yeni/', 'sales.manage'),
    ('/muhasebe/satis/teklifler/', 'sales.manage'),
    ('/muhasebe/stok/', 'accounting.finance'),
    ('/muhasebe/kasa/', 'accounting.finance'),
    ('/muhasebe/hesaplar/', 'accounting.finance'),
    ('/muhasebe/borclar/', 'accounting.finance'),
    ('/muhasebe/proje-karlilik/', 'accounting.finance'),
    ('/muhasebe/dis-aktarim/', 'accounting.finance'),
    ('/muhasebe/zaman/', 'accounting.finance'),
    ('/muhasebe/projeler/yazdir/', ('accounting.finance', 'access.accounting', 'services.manage', 'contact.teams')),
    ('/muhasebe/projeler/', ('accounting.finance', 'access.accounting', 'services.manage', 'contact.teams')),
    ('/muhasebe/alacaklar/', ('sales.reports', 'sales.manage', 'sales.export')),
    ('/muhasebe/satis/raporlar/export-csv/', 'sales.export'),
    ('/muhasebe/satis/raporlar/import-csv/', 'sales.manage'),
    ('/muhasebe/satis/raporlar/yazdir/', 'sales.reports'),
    ('/muhasebe/satis/raporlar/', 'sales.reports'),
    ('/muhasebe/satis/yeni/', 'sales.manage'),
    ('/muhasebe/satis/', 'access.accounting'),
    ('/muhasebe/gelir-gider/import-csv/', 'accounting.finance'),
    ('/muhasebe/gelir-gider/export-csv/', 'accounting.finance'),
    ('/muhasebe/gelir-gider/yazdir/', 'accounting.finance'),
    ('/muhasebe/gelir-gider/', 'accounting.finance'),
    ('/tools/csv/yukle/onizle/', (
        'access.tools', 'access.accounting', 'contact.payroll', 'accounting.finance',
        'sales.manage', 'sales.export', 'contact.customers', 'contact.firms',
    )),
    ('/tools/csv/yukle/ice-aktar/', (
        'access.tools', 'access.accounting', 'contact.payroll', 'accounting.finance',
        'sales.manage', 'sales.export', 'contact.customers', 'contact.firms',
    )),
    ('/tools/csv/yukle/', (
        'access.tools', 'access.accounting', 'contact.payroll', 'accounting.finance',
        'sales.manage', 'sales.export', 'contact.customers', 'contact.firms',
    )),
    ('/tools/csv/', (
        'access.tools', 'access.accounting', 'contact.payroll', 'accounting.finance',
        'sales.manage', 'sales.export', 'sales.reports', 'contact.customers', 'contact.firms',
    )),
    ('/muhasebe/veri-alisverisi/csv/onizle/', (
        'access.accounting', 'contact.payroll', 'accounting.finance',
        'sales.manage', 'sales.export', 'contact.customers', 'contact.firms',
    )),
    ('/muhasebe/veri-alisverisi/csv/ice-aktar/', (
        'access.accounting', 'contact.payroll', 'accounting.finance',
        'sales.manage', 'sales.export', 'contact.customers', 'contact.firms',
    )),
    ('/muhasebe/veri-alisverisi/csv/', (
        'access.accounting', 'contact.payroll', 'accounting.finance',
        'sales.manage', 'sales.export', 'contact.customers', 'contact.firms',
    )),
    ('/muhasebe/veri-alisverisi/', (
        'access.accounting', 'contact.payroll', 'accounting.finance',
        'sales.manage', 'sales.export', 'sales.reports', 'contact.customers', 'contact.firms',
    )),
    ('/contact/musteriler/export-csv/', 'contact.customers'),
    ('/muhasebe/raporlar/', ('access.accounting', 'contact.payroll', 'sales.reports')),
    ('/muhasebe/maas-avans/raporlar/import-csv/', 'contact.payroll'),
    ('/muhasebe/maas-avans/raporlar/export-hareketler/', 'contact.payroll'),
    ('/muhasebe/maas-avans/raporlar/yazdir/', 'contact.payroll'),
    ('/muhasebe/maas-avans/raporlar/export-csv/', 'contact.payroll'),
    ('/muhasebe/maas-avans/raporlar/', 'contact.payroll'),
    ('/muhasebe/maas-avans/', 'contact.payroll'),
    ('/muhasebe/personel/', ('contact.personnel', 'contact.payroll')),
    ('/contact/personel/yonetim/', ('contact.personnel', 'contact.payroll')),
    ('/muhasebe/', 'access.accounting'),
    ('/contact/firma-bul/', 'contact.firms'),
    ('/contact/firma-kazi/', 'contact.firms'),
    ('/contact/personel/', 'contact.personnel'),
    ('/contact/ekip/', 'contact.teams'),
    ('/contact/cozum-agi/', 'contact.firms'),
    ('/contact/firmalar/', 'contact.firms'),
    ('/contact/musteriler/yeni/', 'contact.customers'),
    ('/contact/musteriler/toplu-sil/', 'contact.customers_delete'),
    ('/contact/musteriler/toplu-islem/', 'contact.customers'),
    ('/contact/musteriler/hizli-ekle/', 'contact.customers'),
    ('/contact/musteriler/', ('contact.customers_view', 'contact.customers')),
    ('/contact/pazarlama/personel-mesajlari/', 'access.outreach'),
    ('/contact/pazarlama/musteri-mesajlari/', 'access.outreach'),
    ('/contact/pazarlama/', 'access.outreach'),
    ('/contact/etiketler/', 'access.settings'),
    ('/contact/firmalar/', 'contact.firms'),
    ('/contact/firma-kazi/', 'contact.firms'),
    ('/contact/', 'access.contact'),
    ('/sales-lead/', None),
    ('/tools/api/hava-durumu/', 'access.home'),
    ('/tools/api/ai-chat/', 'tools.ai'),
    ('/tools/medya/sil/', 'tools.media_delete'),
    ('/tools/medya/', 'tools.media'),
    ('/tools/whatsapp-api/', 'tools.whatsapp'),
    ('/tools/whatsapp', 'tools.whatsapp'),
    ('/tools/', 'access.tools'),
    ('/admin/', None),
    ('/media/', None),
    ('/panel/abonelik/modul-toggle/', 'access.home'),
    ('/panel/moduller/toggle/', 'access.home'),
    ('/panel/moduller/', 'access.home'),
    ('/panel/abonelik/', 'access.home'),
    ('/panel/', 'access.home'),
]

LOGIN_EXEMPT_PREFIXES = (
    '/giris/', '/kayit/', '/static/', '/healthz/', '/bilgi-bankasi/',
    '/restoran/api/', '/w/',
)
SUPERUSER_ONLY_PREFIXES = ('/yonetim/',)
