# Generated by Django 5.2.14 on 2026-05-20 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MapsScrapedFirm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_id', models.CharField(blank=True, default='', max_length=128)),
                ('phone_normalized', models.CharField(blank=True, db_index=True, default='', max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField(blank=True, default='')),
                ('phone', models.CharField(blank=True, default='', max_length=40)),
                ('website', models.CharField(blank=True, default='', max_length=500)),
                ('rating', models.CharField(blank=True, default='', max_length=20)),
                ('reviews', models.CharField(blank=True, default='', max_length=20)),
                ('maps_url', models.CharField(blank=True, default='', max_length=500)),
                ('lat', models.CharField(blank=True, default='', max_length=32)),
                ('lng', models.CharField(blank=True, default='', max_length=32)),
                ('first_scraped_at', models.DateTimeField(auto_now_add=True)),
                ('last_scraped_at', models.DateTimeField(auto_now=True)),
                ('messages_sent_count', models.PositiveIntegerField(default=0)),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'verbose_name': 'Maps firması',
                'verbose_name_plural': 'Maps firmaları',
                'ordering': ['-last_scraped_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('place_id', ''), _negated=True), fields=('place_id',), name='tools_mapsfirm_unique_place_id'), models.UniqueConstraint(condition=models.Q(('phone_normalized', ''), _negated=True), fields=('phone_normalized',), name='tools_mapsfirm_unique_phone')],
            },
        ),
        migrations.CreateModel(
            name='WhatsappOutboundMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_name', models.CharField(blank=True, default='', max_length=255)),
                ('phone_normalized', models.CharField(db_index=True, max_length=20)),
                ('phone_display', models.CharField(blank=True, default='', max_length=40)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Bekliyor'), ('sending', 'Gönderiliyor'), ('sent', 'Gönderildi'), ('failed', 'Başarısız'), ('skipped', 'Atlandı')], default='pending', max_length=20)),
                ('source', models.CharField(choices=[('scraped', 'Kazıma'), ('manual', 'Manuel')], default='scraped', max_length=20)),
                ('error_message', models.CharField(blank=True, default='', max_length=500)),
                ('batch_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('firm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outbound_messages', to='tools.mapsscrapedfirm')),
            ],
            options={
                'verbose_name': 'WhatsApp giden mesaj',
                'verbose_name_plural': 'WhatsApp giden mesajlar',
                'ordering': ['id'],
            },
        ),
    ]
