# Generated by Django 5.2.14 on 2026-05-20 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutreachCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Koleksiyon adı')),
                ('message_template', models.TextField(blank=True, default='', verbose_name='Mesaj şablonu')),
                ('skip_globally_messaged', models.BooleanField(default=False, help_text='İşaretliyse daha önce en az bir kez mesaj almış numaralar gönderilmez.', verbose_name='Daha önce mesaj atılanları atla')),
                ('allow_repeat_in_campaign', models.BooleanField(default=True, help_text='Kapalıysa bu koleksiyondan daha önce başarıyla gönderilmiş numaralar atlanır.', verbose_name='Bu kampanyada tekrar gönder')),
                ('delay_seconds', models.PositiveSmallIntegerField(default=4, verbose_name='Mesaj arası bekleme (sn)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Koleksiyon',
                'verbose_name_plural': 'Koleksiyonlar',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='whatsappoutboundmessage',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outbound_messages', to='tools.outreachcollection'),
        ),
        migrations.CreateModel(
            name='OutreachCollectionMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('phone_normalized', models.CharField(db_index=True, max_length=20)),
                ('phone_display', models.CharField(blank=True, default='', max_length=40)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='tools.outreachcollection')),
                ('firm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collection_memberships', to='tools.mapsscrapedfirm')),
            ],
            options={
                'verbose_name': 'Koleksiyon üyesi',
                'verbose_name_plural': 'Koleksiyon üyeleri',
                'ordering': ['id'],
                'constraints': [models.UniqueConstraint(fields=('collection', 'phone_normalized'), name='tools_collection_unique_phone')],
            },
        ),
    ]
