# Generated by Django 5.2.14 on 2026-05-20 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0002_outreachcollection_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirmTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True, verbose_name='Etiket')),
                ('color', models.CharField(default='#6366f1', max_length=7, verbose_name='Renk')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Firma etiketi',
                'verbose_name_plural': 'Firma etiketleri',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='mapsscrapedfirm',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='firms', to='tools.firmtag'),
        ),
    ]
