# Generated by Django 5.2.14 on 2026-05-20 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0003_firmtag_and_firm_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapsscrapedfirm',
            name='region',
            field=models.CharField(blank=True, db_index=True, default='', max_length=80, verbose_name='Bölge'),
        ),
        migrations.AddField(
            model_name='outreachcollectionmember',
            name='custom_message',
            field=models.TextField(blank=True, default='', verbose_name='Özel mesaj'),
        ),
    ]
