# Generated by Django 5.2.14 on 2026-05-20 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0004_region_and_custom_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsappConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Bağlantı adı')),
                ('phone', models.CharField(blank=True, default='', max_length=40)),
                ('pushname', models.CharField(blank=True, default='', max_length=120)),
                ('last_connected_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'WhatsApp bağlantısı',
                'verbose_name_plural': 'WhatsApp bağlantıları',
                'ordering': ['name'],
            },
        ),
    ]
