# Generated by Django 5.2.14 on 2026-06-05 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0007_whatsappoutboundmessage_customer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mapsscrapedfirm',
            options={'ordering': ['-last_scraped_at'], 'verbose_name': 'Firma rehberi', 'verbose_name_plural': 'Firma rehberi'},
        ),
        migrations.AlterField(
            model_name='whatsappoutboundmessage',
            name='source',
            field=models.CharField(choices=[('scraped', 'Kazıma'), ('manual', 'Manuel'), ('auto', 'Otomatik')], default='scraped', max_length=20),
        ),
    ]
