name: Deploy to Firebase and Cloud Run on merge
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_COOLOPS_5A2DE }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Build and Push Container using Cloud Build
        run: |
          gcloud builds submit --tag gcr.io/coolops-5a2de/cool-ops-app --project=coolops-5a2de

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: cool-ops-app
          image: gcr.io/coolops-5a2de/cool-ops-app
          region: us-central1
          flags: '--allow-unauthenticated'
          project_id: coolops-5a2de

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_COOLOPS_5A2DE }}
          channelId: live
          projectId: coolops-5a2de
